### ISSUE TITLE
ctc_loss input error: labels expected to be a SparseTensor

### ISSUE THREAD

**Issue by chutongz** [rajkumarcm15/Speech-Recognition#1]
Hi, I'm working on the speech recognition these day but still new to it.
And when I use your code, something wrong with the ctc_loss.
And I don't know what the label is, like I search on the internet and got some ways to creat a SparseTensor, but I think this label should be doing something with the training data.
So I'm wondering how did you fix this?
Any help is appreciated!
```
Traceback (most recent call last):
  File "MFCC_SWN_BN_Affine/train.py", line 194, in <module>
    loss,error_rate = compute_loss(logits,decoded,targets,seq_lens)
  File "MFCC_SWN_BN_Affine/train.py", line 152, in compute_loss
    loss = tf.reduce_mean(tf.nn.ctc_loss(logits, targets, seq_lens))
  File "/home/chutz/anaconda3/lib/python3.5/site-packages/tensorflow/python/ops/ctc_ops.py", line 145, in ctc_loss
    raise TypeError("Expected labels (first argument) to be a SparseTensor")
TypeError: Expected labels (first argument) to be a SparseTensor
```

**Comment by chutongz** [comment]
Hmmmm, luckly I find out that `train.py L152: loss = tf.reduce_mean(tf.nn.ctc_loss(logits, targets, seq_lens))` is not matching the ctc_loss function, maybe is the version difference. I'm using tensorflow=1.8.0. It requires

>     labels: An `int32` `SparseTensor`.
>       `labels.indices[i, :] == [b, t]` means `labels.values[i]` stores
>       the id for (batch b, time t).
>       `labels.values[i]` must take on values in `[0, num_labels)`.
>       See `core/ops/ctc_ops.cc` for more details.
>     inputs: 3-D `float` `Tensor`.
>       If time_major == False, this will be a `Tensor` shaped:
>         `[batch_size, max_time, num_classes]`.
>       If time_major == True (default), this will be a `Tensor` shaped:
>         `[max_time, batch_size, num_classes]`.
>       The logits.
>     sequence_length: 1-D `int32` vector, size `[batch_size]`.
>       The sequence lengths.

So I fixed this line into:
`loss = tf.reduce_mean(tf.nn.ctc_loss(targets, logits, seq_lens))`

But I am now having another problem:
```
Error/Interruption: slice indices must be integers or None or have an __index__ method
Line no: 238
Current batch: 25
Current epoch: 1
Current step: 0
Clossing TF Session...
Terminating Program...
```
which should be a float-to-int type error, but I couldn't fine the problem operation.
Any help is appreciated! Thanks!

**Comment by chutongz** [comment]
I was using python3.5 and it seems to be version problem too, so I changed into python2.7, but then I got this:
```
Error/Interruption: Cannot feed value of shape (607, 5, 13) for Tensor u'div_2:0', which has shape '(?, 5, 39)'
Line no: 248
Current batch: 10
Current epoch: 1
Current step: 0
```
the train_data.shape  is (607, 5, 13), and the targ_shape is (5, 39)
Could you please give me some detail information about the code?
And also it only has 10 wav files in the train data folder, I changed batch_size into 5, I' not sure whether it will impact the training progress.
